import { randomUUID } from "node:crypto";
import type Stripe from "stripe";
import { getAppUrl, getStripe } from "@/lib/stripe";
import { findOrderById, listOrdersByStripeCheckoutSessionId, requirePool, updateOrderReturnShippingWithProvider } from "@/lib/store";
import { getShippoReturnTracking, purchaseShippoLabelForRate, recoverShippoReturnLabel, type ShippoLabelPurchase, type ShippoShipmentQuote, type ShippoRateOption } from "@/lib/shippo";
import { allocateSellerTransfer, cents, firstAcceptedScan, returnRequestError } from "@/lib/return-policy";

export type ReturnRecord = {
  order_id: string; approved_at: Date; ship_by: Date; accepted_at: Date | null; received_at: Date | null;
  closed_at: Date | null; disputed_at: Date | null; dispute_details: string | null; dispute_evidence: string | null;
  dispute_resolution: string | null; refund_cents: number; seller_cents: number | null; stripe_transfer_id: string | null;
  stripe_refund_id: string | null; stripe_reversal_id: string | null; refund_started_at: Date | null;
  reversal_started_at: Date | null; refund_status: string; recovery_status: string; error: string | null;
};
type LabelPayment = {
  id: string; order_id: string; shipment_id: string; rate_id: string; rate: ShippoRateOption;
  amount_cents: number; stripe_session_id: string | null; stripe_payment_intent_id: string | null;
  status: string; label: ShippoLabelPurchase | null; created_at: Date; error: string | null;
};
const db = () => requirePool();
const message = (e: unknown) => e instanceof Error ? e.message : "Return processing failed";

// A database lease serializes requests across Vercel instances. Persist API intent
// before calling a provider; a lease expiry must never duplicate a purchase.
async function locked<T>(key: string, run: () => Promise<T>): Promise<T> {
  const token = randomUUID();
  const result = await db().query(`INSERT INTO return_workflow_locks(key, token, expires_at)
    VALUES ($1,$2,NOW()+INTERVAL '5 minutes') ON CONFLICT(key) DO UPDATE
    SET token=$2, expires_at=NOW()+INTERVAL '5 minutes' WHERE return_workflow_locks.expires_at < NOW() RETURNING key`, [key, token]);
  if (!result.rowCount) throw new Error("This return is already being processed. Please try again shortly.");
  try { return await run(); }
  finally { await db().query("DELETE FROM return_workflow_locks WHERE key=$1 AND token=$2", [key, token]); }
}
export async function getReturn(orderId: string) {
  return (await db().query<ReturnRecord>("SELECT * FROM order_returns WHERE order_id=$1", [orderId])).rows[0] || null;
}
export async function getReturnLabelPayment(orderId: string) {
  return (await db().query<LabelPayment>("SELECT * FROM return_label_payments WHERE order_id=$1 ORDER BY created_at DESC LIMIT 1", [orderId])).rows[0] || null;
}
async function enqueue(orderId: string, kind: string) {
  await db().query("INSERT INTO return_notification_outbox(id,order_id,kind) VALUES($1,$2,$3) ON CONFLICT DO NOTHING", [`return:${orderId}:${kind}`, orderId, kind]);
}
export async function requestReturn(orderId: string, buyerId: string) {
  return locked(`return:${orderId}`, async () => {
    const order = await findOrderById(orderId);
    if (!order || order.buyerId !== buyerId) throw new Error("Order not found");
    const existing = await getReturn(orderId);
    if (existing) return existing;
    const error = returnRequestError(order);
    if (error) throw new Error(error);
    if (!order.stripePaymentIntentId) throw new Error("Payment confirmation is required before starting a return.");
    // Do not silently rebill buyers for labels generated by the previous system.
    if (order.returnProviderTransactionId) throw new Error("Contact support to process this existing return.");
    await db().query(`WITH inserted AS (
      INSERT INTO order_returns(order_id,refund_cents) VALUES($1,$2) RETURNING order_id)
      UPDATE orders SET return_status='approved', status='issue_open', issue_reason='Return requested by buyer'
      WHERE id IN (SELECT order_id FROM inserted)`, [orderId, cents(order.subtotal)]);
    await enqueue(orderId, "approved");
    return (await getReturn(orderId))!;
  });
}
export async function saveReturnQuote(orderId: string, quote: ShippoShipmentQuote) {
  await db().query("INSERT INTO return_quotes(shipment_id,order_id,rates) VALUES($1,$2,$3) ON CONFLICT DO NOTHING", [quote.shipmentId, orderId, JSON.stringify(quote.rates)]);
}
export async function startReturnLabelCheckout(orderId: string, buyerId: string, shipmentId: string, rateId: string) {
  return locked(`return:${orderId}`, async () => {
    const order = await findOrderById(orderId);
    const ret = await getReturn(orderId);
    if (!order || order.buyerId !== buyerId || !ret || ret.closed_at || ret.accepted_at) throw new Error("Return not available");
    if (Date.now() >= ret.ship_by.getTime()) throw new Error("The 5-day return shipping window has ended. Contact support.");
    if (order.returnProviderTransactionId) throw new Error("A return label already exists.");
    let payment = await getReturnLabelPayment(orderId);
    if (payment?.stripe_session_id && !["expired", "quote_expired"].includes(payment.status)) {
      const session = await getStripe().checkout.sessions.retrieve(payment.stripe_session_id);
      if (session.status === "open" && session.url) return session.url;
      if (session.status !== "expired") throw new Error("Your label payment is processing. Check your purchases shortly.");
      await db().query("UPDATE return_label_payments SET status='expired' WHERE id=$1 AND status='quoted'", [payment.id]);
      payment = await getReturnLabelPayment(orderId);
    }
    if (payment && !["quoted", "expired", "quote_expired"].includes(payment.status)) throw new Error("Your return label is being processed. Contact support if it does not appear.");
    if (!payment || ["expired", "quote_expired"].includes(payment.status)) {
      const quote = (await db().query("SELECT rates FROM return_quotes WHERE shipment_id=$1 AND order_id=$2 AND created_at>NOW()-INTERVAL '30 minutes'", [shipmentId, orderId])).rows[0];
      const rate = (quote?.rates as ShippoRateOption[] | undefined)?.find(r => r.rateId === rateId);
      if (!rate || rate.amount === null || rate.amount <= 0 || rate.currency?.toUpperCase() !== "USD") throw new Error("Refresh the page and select an available USD return rate.");
      payment = (await db().query<LabelPayment>(`INSERT INTO return_label_payments(id,order_id,shipment_id,rate_id,rate,amount_cents)
        VALUES($1,$2,$3,$4,$5,$6) RETURNING *`, [randomUUID(), orderId, shipmentId, rateId, JSON.stringify(rate), cents(rate.amount)])).rows[0];
    }
    // Never recreate an ambiguous Checkout request after Stripe's idempotency retention.
    if (Date.now() - payment.created_at.getTime() > 23 * 3600000) throw new Error("Contact support to recover this label checkout.");
    const session = await getStripe().checkout.sessions.create({
      mode: "payment", payment_method_types: ["card"], client_reference_id: payment.id,
      metadata: { kind: "return_label", returnLabelPaymentId: payment.id, orderId },
      payment_intent_data: { metadata: { kind: "return_label", returnLabelPaymentId: payment.id, orderId } },
      line_items: [{ quantity: 1, price_data: { currency: "usd", unit_amount: payment.amount_cents, product_data: { name: `Return label: ${order.listingTitle}` } } }],
      success_url: `${getAppUrl()}/buyer/orders?saved=return-label-payment`,
      cancel_url: `${getAppUrl()}/buyer/orders/${orderId}/return/shippo`,
      expires_at: Math.floor(payment.created_at.getTime() / 1000) + 3600
    }, { idempotencyKey: `return-label-checkout:${payment.id}` });
    await db().query("UPDATE return_label_payments SET stripe_session_id=$2 WHERE id=$1", [payment.id, session.id]);
    if (!session.url) throw new Error("Checkout is unavailable");
    return session.url;
  });
}

async function saveLabel(payment: LabelPayment, label: ShippoLabelPurchase) {
  // Save provider response before any further work so a crash can resume safely.
  await db().query("UPDATE return_label_payments SET label=$2,shippo_transaction_id=$3,status='label_purchased',error=NULL WHERE id=$1", [payment.id, JSON.stringify(label), label.shippingProviderTransactionId]);
  await updateOrderReturnShippingWithProvider(payment.order_id, {
    carrier: payment.rate.provider, trackingNumber: label.trackingNumber, trackingUrl: label.trackingUrl,
    trackingStatus: label.trackingStatus, returnEta: label.shippingEta,
    returnLabelUrl: label.shippingLabelUrl, returnQrCodeUrl: label.shippingQrCodeUrl,
    returnProvider: "shippo", returnProviderShipmentId: payment.shipment_id, returnProviderRateId: payment.rate_id,
    returnProviderTransactionId: label.shippingProviderTransactionId, sellerNotes: null
  });
  await db().query("UPDATE return_label_payments SET status='complete' WHERE id=$1", [payment.id]);
  await enqueue(payment.order_id, "label_ready");
}
export async function fulfillReturnLabel(session: Stripe.Checkout.Session) {
  const id = session.metadata?.returnLabelPaymentId;
  if (!id) throw new Error("Return label payment reference missing");
  const payment = (await db().query<LabelPayment>("SELECT * FROM return_label_payments WHERE id=$1", [id])).rows[0];
  if (!payment) throw new Error("Return label payment not found");
  return locked(`return:${payment.order_id}`, async () => {
    const p = (await getReturnLabelPayment(payment.order_id))!;
    if (p.id !== id || (p.stripe_session_id && p.stripe_session_id !== session.id)) throw new Error("Return label payment mismatch");
    if (session.payment_status !== "paid") return;
    if (session.amount_total !== p.amount_cents || session.currency !== "usd") throw new Error("Return label payment amount mismatch");
    if (p.status === "complete") { await enqueue(p.order_id, "label_ready"); return; }
    if (p.label) { await saveLabel(p, p.label); return; }
    // A Shippo request cannot be retried safely after an ambiguous response.
    if (["purchasing", "needs_attention"].includes(p.status)) return;
    await db().query("UPDATE return_label_payments SET status='purchasing',stripe_session_id=$2,stripe_payment_intent_id=$3 WHERE id=$1", [id, session.id, typeof session.payment_intent === "string" ? session.payment_intent : session.payment_intent?.id]);
    try {
      const label = await purchaseShippoLabelForRate({ orderId: p.order_id, shipmentId: p.shipment_id, rateId: p.rate_id, rate: p.rate, metadata: `return-label:${id}` });
      await saveLabel(p, label);
    } catch (e) {
      await db().query("UPDATE return_label_payments SET status='needs_attention',error=$2 WHERE id=$1", [id, message(e)]);
      await enqueue(p.order_id, "needs_attention");
      throw e;
    }
  });
}
export async function recoverReturnLabel(orderId: string, transactionId: string) {
  return locked(`return:${orderId}`, async () => {
    const p = await getReturnLabelPayment(orderId);
    if (!p || !p.stripe_payment_intent_id || !["purchasing", "needs_attention"].includes(p.status)) throw new Error("No paid label needs recovery");
    await saveLabel(p, await recoverShippoReturnLabel(transactionId, p.id, p.shipment_id, p.rate_id));
  });
}

async function refundLocked(orderId: string) {
  let ret = (await getReturn(orderId))!;
  const order = await findOrderById(orderId);
  if (!order?.stripePaymentIntentId || !ret.accepted_at) return;
  const stripe = getStripe();
  try {
    const intent = await stripe.paymentIntents.retrieve(order.stripePaymentIntentId, { expand: ["latest_charge.transfer"] });
    if (intent.status !== "succeeded" || intent.currency !== "usd") throw new Error("The original payment is not a successful USD payment.");
    const charge = intent.latest_charge as Stripe.Charge | null;
    if (!charge || typeof charge === "string") throw new Error("Original charge is unavailable");
    if (charge.disputed) throw new Error("An active bank dispute requires manual review before a refund.");
    const transfer = charge.transfer as Stripe.Transfer | null;
    if (!transfer || typeof transfer === "string") throw new Error("Original seller transfer is unavailable");
    if (ret.seller_cents === null) {
      const siblings = order.stripeCheckoutSessionId ? await listOrdersByStripeCheckoutSessionId(order.stripeCheckoutSessionId) : [order];
      if (siblings.reduce((sum, item) => sum + cents(item.amount), 0) !== charge.amount) throw new Error("Payment allocations do not reconcile. Manual review required.");
      const allocation = allocateSellerTransfer(siblings, transfer.amount)[order.id];
      await db().query("UPDATE order_returns SET seller_cents=$2,stripe_transfer_id=$3 WHERE order_id=$1", [orderId, allocation, transfer.id]);
      ret = (await getReturn(orderId))!;
    }
    let refund: Stripe.Refund | undefined;
    if (ret.stripe_refund_id) refund = await stripe.refunds.retrieve(ret.stripe_refund_id);
    else {
      // Recover a succeeded API call whose response was lost before the DB write.
      for await (const candidate of stripe.refunds.list({ payment_intent: intent.id, limit: 100 })) {
        if (candidate.metadata?.tailorgraphReturn === orderId) { refund = candidate; break; }
      }
      if (!refund) {
        if (ret.refund_started_at && Date.now() - ret.refund_started_at.getTime() > 23 * 3600000) throw new Error("Refund result is uncertain; reconcile in Stripe before retrying.");
        if (charge.amount - charge.amount_refunded < ret.refund_cents) throw new Error("The remaining payment is smaller than the full item refund.");
        await db().query("UPDATE order_returns SET refund_started_at=COALESCE(refund_started_at,NOW()),refund_status='processing' WHERE order_id=$1", [orderId]);
        refund = await stripe.refunds.create({ payment_intent: intent.id, amount: ret.refund_cents, reason: "requested_by_customer", metadata: { tailorgraphReturn: orderId } }, { idempotencyKey: `return-refund:${orderId}` });
      }
    }
    if (refund.amount !== ret.refund_cents || refund.payment_intent !== intent.id) throw new Error("Refund does not match this return");
    await db().query("UPDATE order_returns SET stripe_refund_id=$2,refund_status=$3,error=NULL,updated_at=NOW() WHERE order_id=$1", [orderId, refund.id, refund.status || "pending"]);
    if (refund.status !== "succeeded") {
      if (["failed", "canceled", "requires_action"].includes(refund.status || "")) await enqueue(orderId, "needs_attention");
      return;
    }
    await db().query("UPDATE orders SET status='refunded' WHERE id=$1", [orderId]);
    await enqueue(orderId, "refunded");
    if (!ret.stripe_reversal_id && ret.seller_cents! > 0) {
      let reversal: Stripe.TransferReversal | undefined;
      for await (const candidate of stripe.transfers.listReversals(ret.stripe_transfer_id!, { limit: 100 })) {
        if (candidate.metadata?.tailorgraphReturn === orderId) { reversal = candidate; break; }
      }
      if (!reversal) {
        if (ret.reversal_started_at && Date.now() - ret.reversal_started_at.getTime() > 23 * 3600000) throw new Error("Seller recovery needs manual reconciliation before another attempt.");
        await db().query("UPDATE order_returns SET reversal_started_at=COALESCE(reversal_started_at,NOW()),recovery_status='processing' WHERE order_id=$1", [orderId]);
        reversal = await stripe.transfers.createReversal(ret.stripe_transfer_id!, { amount: ret.seller_cents!, metadata: { tailorgraphReturn: orderId } }, { idempotencyKey: `return-reversal:${orderId}` });
      }
      if (reversal.amount !== ret.seller_cents) throw new Error("Seller reversal amount mismatch");
      await db().query("UPDATE order_returns SET stripe_reversal_id=$2,recovery_status='succeeded',error=NULL WHERE order_id=$1", [orderId, reversal.id]);
    } else if (ret.seller_cents === 0) {
      await db().query("UPDATE order_returns SET recovery_status='succeeded' WHERE order_id=$1", [orderId]);
    }
  } catch (e) {
    await db().query("UPDATE order_returns SET error=$2,updated_at=NOW(),recovery_status=CASE WHEN refund_status='succeeded' THEN 'needs_attention' ELSE recovery_status END WHERE order_id=$1", [orderId, message(e)]);
    await enqueue(orderId, "needs_attention");
    throw e;
  }
}
export async function processReturn(orderId: string) {
  return locked(`return:${orderId}`, async () => {
    let ret = await getReturn(orderId);
    const order = await findOrderById(orderId);
    if (!ret || !order) return;
    if (order.returnCarrier && order.returnTrackingNumber && !ret.received_at) {
      // Read tracking back from Shippo. Form fields and webhook payloads never authorize money movement.
      const tracking = await getShippoReturnTracking(order.returnCarrier, order.returnTrackingNumber);
      if (tracking.tracking_number !== order.returnTrackingNumber) throw new Error("Tracking mismatch");
      const scans = [...(tracking.tracking_history || []), ...(tracking.tracking_status ? [tracking.tracking_status] : [])];
      const accepted = firstAcceptedScan(scans, ret.approved_at.toISOString(), ret.ship_by.toISOString());
      if (accepted) await db().query("UPDATE order_returns SET accepted_at=COALESCE(accepted_at,$2) WHERE order_id=$1", [orderId, new Date(accepted)]);
      const delivered = scans.filter(scan => scan.status === "DELIVERED").map(scan => Date.parse(scan.status_date)).filter(time => Number.isFinite(time) && time >= ret!.approved_at.getTime() && time <= Date.now() + 300000).sort((a,b) => a-b)[0];
      if (delivered) {
        await db().query("UPDATE order_returns SET received_at=COALESCE(received_at,$2) WHERE order_id=$1", [orderId, new Date(delivered)]);
        await db().query("UPDATE orders SET return_status='received' WHERE id=$1 AND return_status IS DISTINCT FROM 'closed'", [orderId]);
        await enqueue(orderId, "received");
      } else if (accepted) await db().query("UPDATE orders SET return_status='in_transit' WHERE id=$1 AND return_status NOT IN ('received','closed')", [orderId]);
    }
    ret = (await getReturn(orderId))!;
    if (ret.received_at && !ret.accepted_at) {
      await db().query("UPDATE order_returns SET error='No carrier acceptance within the shipping window. Support must review the tracking history.' WHERE order_id=$1", [orderId]);
      await enqueue(orderId, "needs_attention");
    }
    if (ret.accepted_at && (ret.refund_status !== "succeeded" || ret.recovery_status !== "succeeded")) await refundLocked(orderId);
    await db().query(`WITH closed AS (UPDATE order_returns SET closed_at=NOW()
      WHERE order_id=$1 AND closed_at IS NULL AND disputed_at IS NULL AND refund_status='succeeded'
      AND received_at <= NOW()-INTERVAL '48 hours' RETURNING order_id)
      UPDATE orders SET return_status='closed' WHERE id IN (SELECT order_id FROM closed)`, [orderId]);
    const closed = await getReturn(orderId);
    if (closed?.closed_at && !closed.disputed_at) {
      // Return to a draft for the seller to confirm condition and availability.
      await db().query("UPDATE listings SET status='draft' WHERE id=$1 AND status='sold'", [order.listingId]);
    }
  });
}
export async function disputeReturnedItem(orderId: string, sellerId: string, details: string, evidence: string) {
  return locked(`return:${orderId}`, async () => {
    const order = await findOrderById(orderId);
    const ret = await getReturn(orderId);
    if (!order || order.sellerId !== sellerId || !ret?.received_at || ret.closed_at || ret.disputed_at) throw new Error("This return cannot be disputed.");
    if (Date.now() > ret.received_at.getTime() + 48 * 3600000) throw new Error("The 48-hour inspection window has ended.");
    const urls = evidence.split(/\s+/).filter(Boolean);
    if (details.trim().length < 20 || details.length > 5000 || !urls.length || urls.length > 10 || !urls.every(value => { try { return new URL(value).protocol === "https:"; } catch { return false; } })) throw new Error("Describe the issue (20–5000 characters) and supply 1–10 HTTPS photo or packaging evidence links.");
    await db().query("UPDATE order_returns SET disputed_at=NOW(),dispute_details=$2,dispute_evidence=$3 WHERE order_id=$1", [orderId, details.trim(), urls.join("\n")]);
    await enqueue(orderId, "disputed");
  });
}
export async function acceptReturnedItem(orderId: string, sellerId: string) {
  return locked(`return:${orderId}`, async () => {
    const order = await findOrderById(orderId);
    const ret = await getReturn(orderId);
    if (!order || order.sellerId !== sellerId || !ret?.received_at || ret.disputed_at || ret.refund_status !== "succeeded") throw new Error("This return is not ready to close.");
    await db().query("UPDATE order_returns SET closed_at=COALESCE(closed_at,NOW()) WHERE order_id=$1", [orderId]);
    await db().query("UPDATE orders SET return_status='closed' WHERE id=$1", [orderId]);
    await db().query("UPDATE listings SET status='draft' WHERE id=$1 AND status='sold'", [order.listingId]);
  });
}

export async function reviewReturnDispute(orderId: string, outcome: string, notes: string, adminId: string) {
  if (!["upheld", "declined"].includes(outcome) || notes.trim().length < 20) throw new Error("Choose an outcome and record the review findings (at least 20 characters).");
  return locked(`return:${orderId}`, async () => {
    const ret = await getReturn(orderId);
    const order = await findOrderById(orderId);
    if (!ret?.disputed_at || ret.dispute_resolution || !order) throw new Error("No unresolved return dispute found");
    await db().query("UPDATE order_returns SET dispute_resolution=$2,closed_at=NOW() WHERE order_id=$1", [orderId, `${outcome} by ${adminId}: ${notes.trim()}`]);
    await db().query("UPDATE orders SET return_status='closed' WHERE id=$1", [orderId]);
    await db().query("UPDATE listings SET status=$2 WHERE id=$1 AND status='sold'", [order.listingId, outcome === "upheld" ? "archived" : "draft"]);
    await enqueue(orderId, "reviewed");
  });
}

export async function reconcileReturns() {
  const errors: string[] = [];
  const payments = await db().query<LabelPayment>("SELECT * FROM return_label_payments WHERE status NOT IN ('complete','expired','quote_expired') ORDER BY created_at LIMIT 20");
  for (const p of payments.rows) {
    try {
      if (p.stripe_session_id) {
        const session = await getStripe().checkout.sessions.retrieve(p.stripe_session_id);
        if (session.payment_status === "paid") await fulfillReturnLabel(session);
        else if (session.status === "expired") await db().query("UPDATE return_label_payments SET status='expired' WHERE id=$1 AND status='quoted'", [p.id]);
      }
      if (["purchasing", "needs_attention"].includes(p.status)) await enqueue(p.order_id, "needs_attention");
    } catch (e) { errors.push(`${p.order_id}: ${message(e)}`); }
  }
  const returns = await db().query("SELECT order_id FROM order_returns WHERE closed_at IS NULL OR refund_status <> 'succeeded' OR recovery_status <> 'succeeded' ORDER BY updated_at LIMIT 20");
  for (const row of returns.rows) {
    try { await processReturn(row.order_id); }
    catch (e) { errors.push(`${row.order_id}: ${message(e)}`); }
    finally { await db().query("UPDATE order_returns SET updated_at=NOW() WHERE order_id=$1", [row.order_id]); }
  }
  return { checked: payments.rows.length + returns.rows.length, errors };
}
